#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejra
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ejraDB")]
	public partial class myDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertuserTbl(userTbl instance);
    partial void UpdateuserTbl(userTbl instance);
    partial void DeleteuserTbl(userTbl instance);
    partial void Insertreject(reject instance);
    partial void Updatereject(reject instance);
    partial void Deletereject(reject instance);
    partial void InsertFilesTaxPayer(FilesTaxPayer instance);
    partial void UpdateFilesTaxPayer(FilesTaxPayer instance);
    partial void DeleteFilesTaxPayer(FilesTaxPayer instance);
    #endregion
		
		public myDataClassesDataContext() : 
				base(global::ejra.Properties.Settings.Default.ejraDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public myDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<iegr> iegrs
		{
			get
			{
				return this.GetTable<iegr>();
			}
		}
		
		public System.Data.Linq.Table<userTbl> userTbls
		{
			get
			{
				return this.GetTable<userTbl>();
			}
		}
		
		public System.Data.Linq.Table<reject> rejects
		{
			get
			{
				return this.GetTable<reject>();
			}
		}
		
		public System.Data.Linq.Table<FilesTaxPayer> FilesTaxPayers
		{
			get
			{
				return this.GetTable<FilesTaxPayer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.iegr")]
	public partial class iegr
	{
		
		private System.Nullable<double> _RADIF;
		
		private System.Nullable<double> _KLAS;
		
		private string _NAME;
		
		private string _FNAME;
		
		private string _ADDRESS;
		
		private string _CONAME;
		
		private System.Nullable<short> _SAL;
		
		private System.Nullable<short> _SAL2;
		
		private System.Nullable<double> _MABL;
		
		private System.Nullable<System.DateTime> _DEGR1;
		
		private string _ARSAL;
		
		private System.Nullable<System.DateTime> _DEGR2;
		
		private System.Nullable<System.DateTime> _DEGR3;
		
		private System.Nullable<short> _KODVAZ;
		
		private string _FATHER;
		
		private string _NO_SHEN;
		
		private string _NO_SABT;
		
		private System.Nullable<double> _HOZE;
		
		private System.Nullable<short> _SW;
		
		public iegr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RADIF", DbType="Float")]
		public System.Nullable<double> RADIF
		{
			get
			{
				return this._RADIF;
			}
			set
			{
				if ((this._RADIF != value))
				{
					this._RADIF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KLAS", DbType="Float")]
		public System.Nullable<double> KLAS
		{
			get
			{
				return this._KLAS;
			}
			set
			{
				if ((this._KLAS != value))
				{
					this._KLAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(20)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="NVarChar(30)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this._FNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(30)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONAME", DbType="NVarChar(30)")]
		public string CONAME
		{
			get
			{
				return this._CONAME;
			}
			set
			{
				if ((this._CONAME != value))
				{
					this._CONAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL", DbType="SmallInt")]
		public System.Nullable<short> SAL
		{
			get
			{
				return this._SAL;
			}
			set
			{
				if ((this._SAL != value))
				{
					this._SAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL2", DbType="SmallInt")]
		public System.Nullable<short> SAL2
		{
			get
			{
				return this._SAL2;
			}
			set
			{
				if ((this._SAL2 != value))
				{
					this._SAL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABL", DbType="Float")]
		public System.Nullable<double> MABL
		{
			get
			{
				return this._MABL;
			}
			set
			{
				if ((this._MABL != value))
				{
					this._MABL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGR1", DbType="DateTime")]
		public System.Nullable<System.DateTime> DEGR1
		{
			get
			{
				return this._DEGR1;
			}
			set
			{
				if ((this._DEGR1 != value))
				{
					this._DEGR1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARSAL", DbType="NVarChar(10)")]
		public string ARSAL
		{
			get
			{
				return this._ARSAL;
			}
			set
			{
				if ((this._ARSAL != value))
				{
					this._ARSAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGR2", DbType="DateTime")]
		public System.Nullable<System.DateTime> DEGR2
		{
			get
			{
				return this._DEGR2;
			}
			set
			{
				if ((this._DEGR2 != value))
				{
					this._DEGR2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGR3", DbType="DateTime")]
		public System.Nullable<System.DateTime> DEGR3
		{
			get
			{
				return this._DEGR3;
			}
			set
			{
				if ((this._DEGR3 != value))
				{
					this._DEGR3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KODVAZ", DbType="SmallInt")]
		public System.Nullable<short> KODVAZ
		{
			get
			{
				return this._KODVAZ;
			}
			set
			{
				if ((this._KODVAZ != value))
				{
					this._KODVAZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER", DbType="NVarChar(20)")]
		public string FATHER
		{
			get
			{
				return this._FATHER;
			}
			set
			{
				if ((this._FATHER != value))
				{
					this._FATHER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SHEN", DbType="NVarChar(10)")]
		public string NO_SHEN
		{
			get
			{
				return this._NO_SHEN;
			}
			set
			{
				if ((this._NO_SHEN != value))
				{
					this._NO_SHEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SABT", DbType="NVarChar(10)")]
		public string NO_SABT
		{
			get
			{
				return this._NO_SABT;
			}
			set
			{
				if ((this._NO_SABT != value))
				{
					this._NO_SABT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOZE", DbType="Float")]
		public System.Nullable<double> HOZE
		{
			get
			{
				return this._HOZE;
			}
			set
			{
				if ((this._HOZE != value))
				{
					this._HOZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SW", DbType="SmallInt")]
		public System.Nullable<short> SW
		{
			get
			{
				return this._SW;
			}
			set
			{
				if ((this._SW != value))
				{
					this._SW = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userTbl")]
	public partial class userTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<System.Guid> _UserGuid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnUserGuidChanging(System.Nullable<System.Guid> value);
    partial void OnUserGuidChanged();
    #endregion
		
		public userTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserGuid
		{
			get
			{
				return this._UserGuid;
			}
			set
			{
				if ((this._UserGuid != value))
				{
					this.OnUserGuidChanging(value);
					this.SendPropertyChanging();
					this._UserGuid = value;
					this.SendPropertyChanged("UserGuid");
					this.OnUserGuidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reject")]
	public partial class reject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TARIK;
		
		private System.Nullable<short> _SHOBE;
		
		private string _SAHEB;
		
		private System.Nullable<long> _MABLAG;
		
		private System.Nullable<int> _SAL;
		
		private string _FAMIL;
		
		private string _ADDRESS_1;
		
		private string _comments;
		
		private string _comments2;
		
		private System.Nullable<short> _SHAHR;
		
		private System.Nullable<decimal> _HOZE;
		
		private System.Nullable<short> _MOMAYEZ;
		
		private System.Nullable<short> _NOW_M;
		
		private System.Nullable<int> _PARVANDE;
		
		private System.Nullable<double> _ASL_MAL;
		
		private System.Nullable<double> _SHARDARY;
		
		private System.Nullable<double> _OTAG;
		
		private System.Nullable<double> _JARIME;
		
		private System.Nullable<double> _SAYER;
		
		private System.Nullable<double> _RADIF;
		
		private System.Nullable<double> _SHOMARE;
		
		private string _TARIK_2;
		
		private string _SH_CHEK;
		
		private string _HESAB_J;
		
		private System.Nullable<short> _MAHAL;
		
		private System.Nullable<int> _MABLAG_BAN;
		
		private System.Nullable<int> _TARTIB_BAN;
		
		private string _TARIK_3;
		
		private System.Nullable<double> _CONTROL;
		
		private string _SERI;
		
		private System.Nullable<short> _CODE;
		
		private string _SHOBE2;
		
		private bool _REJECT1;
		
		private string _DES_REJECT;
		
		private string _DE2_REJECT;
		
		private string _DE3_REJECT;
		
		private string _DAT_REJECT;
		
		private string _DATE_ERSAL;
		
		private string _DATE_VOSOL;
		
		private bool _ERSAL;
		
		private string _DATE_ACT;
		
		private string _OPRATOR;
		
		private bool _PAS;
		
		private System.Nullable<short> _TAG;
		
		private bool _COP;
		
		private System.Nullable<short> _AMAL;
		
		private string _NAME;
		
		private string _TAG2;
		
		private string _NO_SHEN;
		
		private string _NO_SABT;
		
		private string _HOG;
		
		private string _FATHER;
		
		private System.Nullable<short> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTARIKChanging(string value);
    partial void OnTARIKChanged();
    partial void OnSHOBEChanging(System.Nullable<short> value);
    partial void OnSHOBEChanged();
    partial void OnSAHEBChanging(string value);
    partial void OnSAHEBChanged();
    partial void OnMABLAGChanging(System.Nullable<long> value);
    partial void OnMABLAGChanged();
    partial void OnSALChanging(System.Nullable<int> value);
    partial void OnSALChanged();
    partial void OnFAMILChanging(string value);
    partial void OnFAMILChanged();
    partial void OnADDRESS_1Changing(string value);
    partial void OnADDRESS_1Changed();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void Oncomments2Changing(string value);
    partial void Oncomments2Changed();
    partial void OnSHAHRChanging(System.Nullable<short> value);
    partial void OnSHAHRChanged();
    partial void OnHOZEChanging(System.Nullable<decimal> value);
    partial void OnHOZEChanged();
    partial void OnMOMAYEZChanging(System.Nullable<short> value);
    partial void OnMOMAYEZChanged();
    partial void OnNOW_MChanging(System.Nullable<short> value);
    partial void OnNOW_MChanged();
    partial void OnPARVANDEChanging(System.Nullable<int> value);
    partial void OnPARVANDEChanged();
    partial void OnASL_MALChanging(System.Nullable<double> value);
    partial void OnASL_MALChanged();
    partial void OnSHARDARYChanging(System.Nullable<double> value);
    partial void OnSHARDARYChanged();
    partial void OnOTAGChanging(System.Nullable<double> value);
    partial void OnOTAGChanged();
    partial void OnJARIMEChanging(System.Nullable<double> value);
    partial void OnJARIMEChanged();
    partial void OnSAYERChanging(System.Nullable<double> value);
    partial void OnSAYERChanged();
    partial void OnRADIFChanging(System.Nullable<double> value);
    partial void OnRADIFChanged();
    partial void OnSHOMAREChanging(System.Nullable<double> value);
    partial void OnSHOMAREChanged();
    partial void OnTARIK_2Changing(string value);
    partial void OnTARIK_2Changed();
    partial void OnSH_CHEKChanging(string value);
    partial void OnSH_CHEKChanged();
    partial void OnHESAB_JChanging(string value);
    partial void OnHESAB_JChanged();
    partial void OnMAHALChanging(System.Nullable<short> value);
    partial void OnMAHALChanged();
    partial void OnMABLAG_BANChanging(System.Nullable<int> value);
    partial void OnMABLAG_BANChanged();
    partial void OnTARTIB_BANChanging(System.Nullable<int> value);
    partial void OnTARTIB_BANChanged();
    partial void OnTARIK_3Changing(string value);
    partial void OnTARIK_3Changed();
    partial void OnCONTROLChanging(System.Nullable<double> value);
    partial void OnCONTROLChanged();
    partial void OnSERIChanging(string value);
    partial void OnSERIChanged();
    partial void OnCODEChanging(System.Nullable<short> value);
    partial void OnCODEChanged();
    partial void OnSHOBE2Changing(string value);
    partial void OnSHOBE2Changed();
    partial void OnREJECT1Changing(bool value);
    partial void OnREJECT1Changed();
    partial void OnDES_REJECTChanging(string value);
    partial void OnDES_REJECTChanged();
    partial void OnDE2_REJECTChanging(string value);
    partial void OnDE2_REJECTChanged();
    partial void OnDE3_REJECTChanging(string value);
    partial void OnDE3_REJECTChanged();
    partial void OnDAT_REJECTChanging(string value);
    partial void OnDAT_REJECTChanged();
    partial void OnDATE_ERSALChanging(string value);
    partial void OnDATE_ERSALChanged();
    partial void OnDATE_VOSOLChanging(string value);
    partial void OnDATE_VOSOLChanged();
    partial void OnERSALChanging(bool value);
    partial void OnERSALChanged();
    partial void OnDATE_ACTChanging(string value);
    partial void OnDATE_ACTChanged();
    partial void OnOPRATORChanging(string value);
    partial void OnOPRATORChanged();
    partial void OnPASChanging(bool value);
    partial void OnPASChanged();
    partial void OnTAGChanging(System.Nullable<short> value);
    partial void OnTAGChanged();
    partial void OnCOPChanging(bool value);
    partial void OnCOPChanged();
    partial void OnAMALChanging(System.Nullable<short> value);
    partial void OnAMALChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnTAG2Changing(string value);
    partial void OnTAG2Changed();
    partial void OnNO_SHENChanging(string value);
    partial void OnNO_SHENChanged();
    partial void OnNO_SABTChanging(string value);
    partial void OnNO_SABTChanged();
    partial void OnHOGChanging(string value);
    partial void OnHOGChanged();
    partial void OnFATHERChanging(string value);
    partial void OnFATHERChanged();
    partial void OnstatusChanging(System.Nullable<short> value);
    partial void OnstatusChanged();
    #endregion
		
		public reject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIK", DbType="VarChar(50)")]
		public string TARIK
		{
			get
			{
				return this._TARIK;
			}
			set
			{
				if ((this._TARIK != value))
				{
					this.OnTARIKChanging(value);
					this.SendPropertyChanging();
					this._TARIK = value;
					this.SendPropertyChanged("TARIK");
					this.OnTARIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOBE", DbType="SmallInt")]
		public System.Nullable<short> SHOBE
		{
			get
			{
				return this._SHOBE;
			}
			set
			{
				if ((this._SHOBE != value))
				{
					this.OnSHOBEChanging(value);
					this.SendPropertyChanging();
					this._SHOBE = value;
					this.SendPropertyChanged("SHOBE");
					this.OnSHOBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAHEB", DbType="NVarChar(2)")]
		public string SAHEB
		{
			get
			{
				return this._SAHEB;
			}
			set
			{
				if ((this._SAHEB != value))
				{
					this.OnSAHEBChanging(value);
					this.SendPropertyChanging();
					this._SAHEB = value;
					this.SendPropertyChanged("SAHEB");
					this.OnSAHEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABLAG", DbType="BigInt")]
		public System.Nullable<long> MABLAG
		{
			get
			{
				return this._MABLAG;
			}
			set
			{
				if ((this._MABLAG != value))
				{
					this.OnMABLAGChanging(value);
					this.SendPropertyChanging();
					this._MABLAG = value;
					this.SendPropertyChanged("MABLAG");
					this.OnMABLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL", DbType="Int")]
		public System.Nullable<int> SAL
		{
			get
			{
				return this._SAL;
			}
			set
			{
				if ((this._SAL != value))
				{
					this.OnSALChanging(value);
					this.SendPropertyChanging();
					this._SAL = value;
					this.SendPropertyChanged("SAL");
					this.OnSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAMIL", DbType="NVarChar(40)")]
		public string FAMIL
		{
			get
			{
				return this._FAMIL;
			}
			set
			{
				if ((this._FAMIL != value))
				{
					this.OnFAMILChanging(value);
					this.SendPropertyChanging();
					this._FAMIL = value;
					this.SendPropertyChanged("FAMIL");
					this.OnFAMILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_1", DbType="NVarChar(100)")]
		public string ADDRESS_1
		{
			get
			{
				return this._ADDRESS_1;
			}
			set
			{
				if ((this._ADDRESS_1 != value))
				{
					this.OnADDRESS_1Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS_1 = value;
					this.SendPropertyChanged("ADDRESS_1");
					this.OnADDRESS_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(100)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments2", DbType="NVarChar(100)")]
		public string comments2
		{
			get
			{
				return this._comments2;
			}
			set
			{
				if ((this._comments2 != value))
				{
					this.Oncomments2Changing(value);
					this.SendPropertyChanging();
					this._comments2 = value;
					this.SendPropertyChanged("comments2");
					this.Oncomments2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHAHR", DbType="SmallInt")]
		public System.Nullable<short> SHAHR
		{
			get
			{
				return this._SHAHR;
			}
			set
			{
				if ((this._SHAHR != value))
				{
					this.OnSHAHRChanging(value);
					this.SendPropertyChanging();
					this._SHAHR = value;
					this.SendPropertyChanged("SHAHR");
					this.OnSHAHRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOZE", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> HOZE
		{
			get
			{
				return this._HOZE;
			}
			set
			{
				if ((this._HOZE != value))
				{
					this.OnHOZEChanging(value);
					this.SendPropertyChanging();
					this._HOZE = value;
					this.SendPropertyChanged("HOZE");
					this.OnHOZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOMAYEZ", DbType="SmallInt")]
		public System.Nullable<short> MOMAYEZ
		{
			get
			{
				return this._MOMAYEZ;
			}
			set
			{
				if ((this._MOMAYEZ != value))
				{
					this.OnMOMAYEZChanging(value);
					this.SendPropertyChanging();
					this._MOMAYEZ = value;
					this.SendPropertyChanged("MOMAYEZ");
					this.OnMOMAYEZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOW_M", DbType="SmallInt")]
		public System.Nullable<short> NOW_M
		{
			get
			{
				return this._NOW_M;
			}
			set
			{
				if ((this._NOW_M != value))
				{
					this.OnNOW_MChanging(value);
					this.SendPropertyChanging();
					this._NOW_M = value;
					this.SendPropertyChanged("NOW_M");
					this.OnNOW_MChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARVANDE", DbType="Int")]
		public System.Nullable<int> PARVANDE
		{
			get
			{
				return this._PARVANDE;
			}
			set
			{
				if ((this._PARVANDE != value))
				{
					this.OnPARVANDEChanging(value);
					this.SendPropertyChanging();
					this._PARVANDE = value;
					this.SendPropertyChanged("PARVANDE");
					this.OnPARVANDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASL_MAL", DbType="Float")]
		public System.Nullable<double> ASL_MAL
		{
			get
			{
				return this._ASL_MAL;
			}
			set
			{
				if ((this._ASL_MAL != value))
				{
					this.OnASL_MALChanging(value);
					this.SendPropertyChanging();
					this._ASL_MAL = value;
					this.SendPropertyChanged("ASL_MAL");
					this.OnASL_MALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHARDARY", DbType="Float")]
		public System.Nullable<double> SHARDARY
		{
			get
			{
				return this._SHARDARY;
			}
			set
			{
				if ((this._SHARDARY != value))
				{
					this.OnSHARDARYChanging(value);
					this.SendPropertyChanging();
					this._SHARDARY = value;
					this.SendPropertyChanged("SHARDARY");
					this.OnSHARDARYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTAG", DbType="Float")]
		public System.Nullable<double> OTAG
		{
			get
			{
				return this._OTAG;
			}
			set
			{
				if ((this._OTAG != value))
				{
					this.OnOTAGChanging(value);
					this.SendPropertyChanging();
					this._OTAG = value;
					this.SendPropertyChanged("OTAG");
					this.OnOTAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JARIME", DbType="Float")]
		public System.Nullable<double> JARIME
		{
			get
			{
				return this._JARIME;
			}
			set
			{
				if ((this._JARIME != value))
				{
					this.OnJARIMEChanging(value);
					this.SendPropertyChanging();
					this._JARIME = value;
					this.SendPropertyChanged("JARIME");
					this.OnJARIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAYER", DbType="Float")]
		public System.Nullable<double> SAYER
		{
			get
			{
				return this._SAYER;
			}
			set
			{
				if ((this._SAYER != value))
				{
					this.OnSAYERChanging(value);
					this.SendPropertyChanging();
					this._SAYER = value;
					this.SendPropertyChanged("SAYER");
					this.OnSAYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RADIF", DbType="Float")]
		public System.Nullable<double> RADIF
		{
			get
			{
				return this._RADIF;
			}
			set
			{
				if ((this._RADIF != value))
				{
					this.OnRADIFChanging(value);
					this.SendPropertyChanging();
					this._RADIF = value;
					this.SendPropertyChanged("RADIF");
					this.OnRADIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOMARE", DbType="Float")]
		public System.Nullable<double> SHOMARE
		{
			get
			{
				return this._SHOMARE;
			}
			set
			{
				if ((this._SHOMARE != value))
				{
					this.OnSHOMAREChanging(value);
					this.SendPropertyChanging();
					this._SHOMARE = value;
					this.SendPropertyChanged("SHOMARE");
					this.OnSHOMAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIK_2", DbType="VarChar(10)")]
		public string TARIK_2
		{
			get
			{
				return this._TARIK_2;
			}
			set
			{
				if ((this._TARIK_2 != value))
				{
					this.OnTARIK_2Changing(value);
					this.SendPropertyChanging();
					this._TARIK_2 = value;
					this.SendPropertyChanged("TARIK_2");
					this.OnTARIK_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SH_CHEK", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SH_CHEK
		{
			get
			{
				return this._SH_CHEK;
			}
			set
			{
				if ((this._SH_CHEK != value))
				{
					this.OnSH_CHEKChanging(value);
					this.SendPropertyChanging();
					this._SH_CHEK = value;
					this.SendPropertyChanged("SH_CHEK");
					this.OnSH_CHEKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAB_J", DbType="NVarChar(10)")]
		public string HESAB_J
		{
			get
			{
				return this._HESAB_J;
			}
			set
			{
				if ((this._HESAB_J != value))
				{
					this.OnHESAB_JChanging(value);
					this.SendPropertyChanging();
					this._HESAB_J = value;
					this.SendPropertyChanged("HESAB_J");
					this.OnHESAB_JChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHAL", DbType="SmallInt")]
		public System.Nullable<short> MAHAL
		{
			get
			{
				return this._MAHAL;
			}
			set
			{
				if ((this._MAHAL != value))
				{
					this.OnMAHALChanging(value);
					this.SendPropertyChanging();
					this._MAHAL = value;
					this.SendPropertyChanged("MAHAL");
					this.OnMAHALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABLAG_BAN", DbType="Int")]
		public System.Nullable<int> MABLAG_BAN
		{
			get
			{
				return this._MABLAG_BAN;
			}
			set
			{
				if ((this._MABLAG_BAN != value))
				{
					this.OnMABLAG_BANChanging(value);
					this.SendPropertyChanging();
					this._MABLAG_BAN = value;
					this.SendPropertyChanged("MABLAG_BAN");
					this.OnMABLAG_BANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARTIB_BAN", DbType="Int")]
		public System.Nullable<int> TARTIB_BAN
		{
			get
			{
				return this._TARTIB_BAN;
			}
			set
			{
				if ((this._TARTIB_BAN != value))
				{
					this.OnTARTIB_BANChanging(value);
					this.SendPropertyChanging();
					this._TARTIB_BAN = value;
					this.SendPropertyChanged("TARTIB_BAN");
					this.OnTARTIB_BANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIK_3", DbType="VarChar(10)")]
		public string TARIK_3
		{
			get
			{
				return this._TARIK_3;
			}
			set
			{
				if ((this._TARIK_3 != value))
				{
					this.OnTARIK_3Changing(value);
					this.SendPropertyChanging();
					this._TARIK_3 = value;
					this.SendPropertyChanged("TARIK_3");
					this.OnTARIK_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROL", DbType="Float")]
		public System.Nullable<double> CONTROL
		{
			get
			{
				return this._CONTROL;
			}
			set
			{
				if ((this._CONTROL != value))
				{
					this.OnCONTROLChanging(value);
					this.SendPropertyChanging();
					this._CONTROL = value;
					this.SendPropertyChanged("CONTROL");
					this.OnCONTROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERI", DbType="NVarChar(3)")]
		public string SERI
		{
			get
			{
				return this._SERI;
			}
			set
			{
				if ((this._SERI != value))
				{
					this.OnSERIChanging(value);
					this.SendPropertyChanging();
					this._SERI = value;
					this.SendPropertyChanged("SERI");
					this.OnSERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="SmallInt")]
		public System.Nullable<short> CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOBE2", DbType="NVarChar(15)")]
		public string SHOBE2
		{
			get
			{
				return this._SHOBE2;
			}
			set
			{
				if ((this._SHOBE2 != value))
				{
					this.OnSHOBE2Changing(value);
					this.SendPropertyChanging();
					this._SHOBE2 = value;
					this.SendPropertyChanged("SHOBE2");
					this.OnSHOBE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="REJECT", Storage="_REJECT1", DbType="Bit NOT NULL")]
		public bool REJECT1
		{
			get
			{
				return this._REJECT1;
			}
			set
			{
				if ((this._REJECT1 != value))
				{
					this.OnREJECT1Changing(value);
					this.SendPropertyChanging();
					this._REJECT1 = value;
					this.SendPropertyChanged("REJECT1");
					this.OnREJECT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DES_REJECT", DbType="NVarChar(30)")]
		public string DES_REJECT
		{
			get
			{
				return this._DES_REJECT;
			}
			set
			{
				if ((this._DES_REJECT != value))
				{
					this.OnDES_REJECTChanging(value);
					this.SendPropertyChanging();
					this._DES_REJECT = value;
					this.SendPropertyChanged("DES_REJECT");
					this.OnDES_REJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DE2_REJECT", DbType="NVarChar(30)")]
		public string DE2_REJECT
		{
			get
			{
				return this._DE2_REJECT;
			}
			set
			{
				if ((this._DE2_REJECT != value))
				{
					this.OnDE2_REJECTChanging(value);
					this.SendPropertyChanging();
					this._DE2_REJECT = value;
					this.SendPropertyChanged("DE2_REJECT");
					this.OnDE2_REJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DE3_REJECT", DbType="NVarChar(30)")]
		public string DE3_REJECT
		{
			get
			{
				return this._DE3_REJECT;
			}
			set
			{
				if ((this._DE3_REJECT != value))
				{
					this.OnDE3_REJECTChanging(value);
					this.SendPropertyChanging();
					this._DE3_REJECT = value;
					this.SendPropertyChanged("DE3_REJECT");
					this.OnDE3_REJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAT_REJECT", DbType="VarChar(10)")]
		public string DAT_REJECT
		{
			get
			{
				return this._DAT_REJECT;
			}
			set
			{
				if ((this._DAT_REJECT != value))
				{
					this.OnDAT_REJECTChanging(value);
					this.SendPropertyChanging();
					this._DAT_REJECT = value;
					this.SendPropertyChanged("DAT_REJECT");
					this.OnDAT_REJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_ERSAL", DbType="VarChar(10)")]
		public string DATE_ERSAL
		{
			get
			{
				return this._DATE_ERSAL;
			}
			set
			{
				if ((this._DATE_ERSAL != value))
				{
					this.OnDATE_ERSALChanging(value);
					this.SendPropertyChanging();
					this._DATE_ERSAL = value;
					this.SendPropertyChanged("DATE_ERSAL");
					this.OnDATE_ERSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_VOSOL", DbType="VarChar(10)")]
		public string DATE_VOSOL
		{
			get
			{
				return this._DATE_VOSOL;
			}
			set
			{
				if ((this._DATE_VOSOL != value))
				{
					this.OnDATE_VOSOLChanging(value);
					this.SendPropertyChanging();
					this._DATE_VOSOL = value;
					this.SendPropertyChanged("DATE_VOSOL");
					this.OnDATE_VOSOLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERSAL", DbType="Bit NOT NULL")]
		public bool ERSAL
		{
			get
			{
				return this._ERSAL;
			}
			set
			{
				if ((this._ERSAL != value))
				{
					this.OnERSALChanging(value);
					this.SendPropertyChanging();
					this._ERSAL = value;
					this.SendPropertyChanged("ERSAL");
					this.OnERSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_ACT", DbType="VarChar(10)")]
		public string DATE_ACT
		{
			get
			{
				return this._DATE_ACT;
			}
			set
			{
				if ((this._DATE_ACT != value))
				{
					this.OnDATE_ACTChanging(value);
					this.SendPropertyChanging();
					this._DATE_ACT = value;
					this.SendPropertyChanged("DATE_ACT");
					this.OnDATE_ACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPRATOR", DbType="NVarChar(2)")]
		public string OPRATOR
		{
			get
			{
				return this._OPRATOR;
			}
			set
			{
				if ((this._OPRATOR != value))
				{
					this.OnOPRATORChanging(value);
					this.SendPropertyChanging();
					this._OPRATOR = value;
					this.SendPropertyChanged("OPRATOR");
					this.OnOPRATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAS", DbType="Bit NOT NULL")]
		public bool PAS
		{
			get
			{
				return this._PAS;
			}
			set
			{
				if ((this._PAS != value))
				{
					this.OnPASChanging(value);
					this.SendPropertyChanging();
					this._PAS = value;
					this.SendPropertyChanged("PAS");
					this.OnPASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG", DbType="SmallInt")]
		public System.Nullable<short> TAG
		{
			get
			{
				return this._TAG;
			}
			set
			{
				if ((this._TAG != value))
				{
					this.OnTAGChanging(value);
					this.SendPropertyChanging();
					this._TAG = value;
					this.SendPropertyChanged("TAG");
					this.OnTAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COP", DbType="Bit NOT NULL")]
		public bool COP
		{
			get
			{
				return this._COP;
			}
			set
			{
				if ((this._COP != value))
				{
					this.OnCOPChanging(value);
					this.SendPropertyChanging();
					this._COP = value;
					this.SendPropertyChanged("COP");
					this.OnCOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMAL", DbType="SmallInt")]
		public System.Nullable<short> AMAL
		{
			get
			{
				return this._AMAL;
			}
			set
			{
				if ((this._AMAL != value))
				{
					this.OnAMALChanging(value);
					this.SendPropertyChanging();
					this._AMAL = value;
					this.SendPropertyChanged("AMAL");
					this.OnAMALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(20)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG2", DbType="NVarChar(2)")]
		public string TAG2
		{
			get
			{
				return this._TAG2;
			}
			set
			{
				if ((this._TAG2 != value))
				{
					this.OnTAG2Changing(value);
					this.SendPropertyChanging();
					this._TAG2 = value;
					this.SendPropertyChanged("TAG2");
					this.OnTAG2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SHEN", DbType="NVarChar(10)")]
		public string NO_SHEN
		{
			get
			{
				return this._NO_SHEN;
			}
			set
			{
				if ((this._NO_SHEN != value))
				{
					this.OnNO_SHENChanging(value);
					this.SendPropertyChanging();
					this._NO_SHEN = value;
					this.SendPropertyChanged("NO_SHEN");
					this.OnNO_SHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SABT", DbType="VarChar(12)")]
		public string NO_SABT
		{
			get
			{
				return this._NO_SABT;
			}
			set
			{
				if ((this._NO_SABT != value))
				{
					this.OnNO_SABTChanging(value);
					this.SendPropertyChanging();
					this._NO_SABT = value;
					this.SendPropertyChanged("NO_SABT");
					this.OnNO_SABTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOG", DbType="NVarChar(1)")]
		public string HOG
		{
			get
			{
				return this._HOG;
			}
			set
			{
				if ((this._HOG != value))
				{
					this.OnHOGChanging(value);
					this.SendPropertyChanging();
					this._HOG = value;
					this.SendPropertyChanged("HOG");
					this.OnHOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER", DbType="NVarChar(20)")]
		public string FATHER
		{
			get
			{
				return this._FATHER;
			}
			set
			{
				if ((this._FATHER != value))
				{
					this.OnFATHERChanging(value);
					this.SendPropertyChanging();
					this._FATHER = value;
					this.SendPropertyChanged("FATHER");
					this.OnFATHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt")]
		public System.Nullable<short> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FilesTaxPayer")]
	public partial class FilesTaxPayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _KLAS;
		
		private string _NAME;
		
		private string _FNAME;
		
		private string _ADDRESS;
		
		private string _CONAME;
		
		private string _SAL;
		
		private string _SAL2;
		
		private System.Nullable<long> _MABL;
		
		private string _DEGR1;
		
		private string _ARSAL;
		
		private string _DEGR2;
		
		private string _DEGR3;
		
		private System.Nullable<short> _KODVAZ;
		
		private string _FATHER;
		
		private string _NO_SHEN;
		
		private string _NO_SABT;
		
		private System.Nullable<decimal> _HOZE;
		
		private string _pdegr1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKLASChanging(string value);
    partial void OnKLASChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnFNAMEChanging(string value);
    partial void OnFNAMEChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnCONAMEChanging(string value);
    partial void OnCONAMEChanged();
    partial void OnSALChanging(string value);
    partial void OnSALChanged();
    partial void OnSAL2Changing(string value);
    partial void OnSAL2Changed();
    partial void OnMABLChanging(System.Nullable<long> value);
    partial void OnMABLChanged();
    partial void OnDEGR1Changing(string value);
    partial void OnDEGR1Changed();
    partial void OnARSALChanging(string value);
    partial void OnARSALChanged();
    partial void OnDEGR2Changing(string value);
    partial void OnDEGR2Changed();
    partial void OnDEGR3Changing(string value);
    partial void OnDEGR3Changed();
    partial void OnKODVAZChanging(System.Nullable<short> value);
    partial void OnKODVAZChanged();
    partial void OnFATHERChanging(string value);
    partial void OnFATHERChanged();
    partial void OnNO_SHENChanging(string value);
    partial void OnNO_SHENChanged();
    partial void OnNO_SABTChanging(string value);
    partial void OnNO_SABTChanged();
    partial void OnHOZEChanging(System.Nullable<decimal> value);
    partial void OnHOZEChanged();
    partial void Onpdegr1Changing(string value);
    partial void Onpdegr1Changed();
    #endregion
		
		public FilesTaxPayer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KLAS", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string KLAS
		{
			get
			{
				return this._KLAS;
			}
			set
			{
				if ((this._KLAS != value))
				{
					this.OnKLASChanging(value);
					this.SendPropertyChanging();
					this._KLAS = value;
					this.SendPropertyChanged("KLAS");
					this.OnKLASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(20)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="NVarChar(30)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this.OnFNAMEChanging(value);
					this.SendPropertyChanging();
					this._FNAME = value;
					this.SendPropertyChanged("FNAME");
					this.OnFNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(500)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONAME", DbType="NVarChar(100)")]
		public string CONAME
		{
			get
			{
				return this._CONAME;
			}
			set
			{
				if ((this._CONAME != value))
				{
					this.OnCONAMEChanging(value);
					this.SendPropertyChanging();
					this._CONAME = value;
					this.SendPropertyChanged("CONAME");
					this.OnCONAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL", DbType="Char(4)")]
		public string SAL
		{
			get
			{
				return this._SAL;
			}
			set
			{
				if ((this._SAL != value))
				{
					this.OnSALChanging(value);
					this.SendPropertyChanging();
					this._SAL = value;
					this.SendPropertyChanged("SAL");
					this.OnSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAL2", DbType="Char(4)")]
		public string SAL2
		{
			get
			{
				return this._SAL2;
			}
			set
			{
				if ((this._SAL2 != value))
				{
					this.OnSAL2Changing(value);
					this.SendPropertyChanging();
					this._SAL2 = value;
					this.SendPropertyChanged("SAL2");
					this.OnSAL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABL", DbType="BigInt")]
		public System.Nullable<long> MABL
		{
			get
			{
				return this._MABL;
			}
			set
			{
				if ((this._MABL != value))
				{
					this.OnMABLChanging(value);
					this.SendPropertyChanging();
					this._MABL = value;
					this.SendPropertyChanged("MABL");
					this.OnMABLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGR1", DbType="VarChar(10)")]
		public string DEGR1
		{
			get
			{
				return this._DEGR1;
			}
			set
			{
				if ((this._DEGR1 != value))
				{
					this.OnDEGR1Changing(value);
					this.SendPropertyChanging();
					this._DEGR1 = value;
					this.SendPropertyChanged("DEGR1");
					this.OnDEGR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARSAL", DbType="Char(10)")]
		public string ARSAL
		{
			get
			{
				return this._ARSAL;
			}
			set
			{
				if ((this._ARSAL != value))
				{
					this.OnARSALChanging(value);
					this.SendPropertyChanging();
					this._ARSAL = value;
					this.SendPropertyChanged("ARSAL");
					this.OnARSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGR2", DbType="VarChar(10)")]
		public string DEGR2
		{
			get
			{
				return this._DEGR2;
			}
			set
			{
				if ((this._DEGR2 != value))
				{
					this.OnDEGR2Changing(value);
					this.SendPropertyChanging();
					this._DEGR2 = value;
					this.SendPropertyChanged("DEGR2");
					this.OnDEGR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGR3", DbType="VarChar(50)")]
		public string DEGR3
		{
			get
			{
				return this._DEGR3;
			}
			set
			{
				if ((this._DEGR3 != value))
				{
					this.OnDEGR3Changing(value);
					this.SendPropertyChanging();
					this._DEGR3 = value;
					this.SendPropertyChanged("DEGR3");
					this.OnDEGR3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KODVAZ", DbType="SmallInt")]
		public System.Nullable<short> KODVAZ
		{
			get
			{
				return this._KODVAZ;
			}
			set
			{
				if ((this._KODVAZ != value))
				{
					this.OnKODVAZChanging(value);
					this.SendPropertyChanging();
					this._KODVAZ = value;
					this.SendPropertyChanged("KODVAZ");
					this.OnKODVAZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER", DbType="NVarChar(20)")]
		public string FATHER
		{
			get
			{
				return this._FATHER;
			}
			set
			{
				if ((this._FATHER != value))
				{
					this.OnFATHERChanging(value);
					this.SendPropertyChanging();
					this._FATHER = value;
					this.SendPropertyChanged("FATHER");
					this.OnFATHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SHEN", DbType="Char(10)")]
		public string NO_SHEN
		{
			get
			{
				return this._NO_SHEN;
			}
			set
			{
				if ((this._NO_SHEN != value))
				{
					this.OnNO_SHENChanging(value);
					this.SendPropertyChanging();
					this._NO_SHEN = value;
					this.SendPropertyChanged("NO_SHEN");
					this.OnNO_SHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SABT", DbType="Char(10)")]
		public string NO_SABT
		{
			get
			{
				return this._NO_SABT;
			}
			set
			{
				if ((this._NO_SABT != value))
				{
					this.OnNO_SABTChanging(value);
					this.SendPropertyChanging();
					this._NO_SABT = value;
					this.SendPropertyChanged("NO_SABT");
					this.OnNO_SABTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOZE", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> HOZE
		{
			get
			{
				return this._HOZE;
			}
			set
			{
				if ((this._HOZE != value))
				{
					this.OnHOZEChanging(value);
					this.SendPropertyChanging();
					this._HOZE = value;
					this.SendPropertyChanged("HOZE");
					this.OnHOZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdegr1", DbType="VarChar(10)")]
		public string pdegr1
		{
			get
			{
				return this._pdegr1;
			}
			set
			{
				if ((this._pdegr1 != value))
				{
					this.Onpdegr1Changing(value);
					this.SendPropertyChanging();
					this._pdegr1 = value;
					this.SendPropertyChanged("pdegr1");
					this.Onpdegr1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
